INSERT INTO fpgrades(Name) VALUES ('Basica');
INSERT INTO fpgrades(Name) VALUES ('Media');
INSERT INTO fpgrades(Name) VALUES ('Superior');
INSERT INTO fpgrades(Name) VALUES ('Especializacion');

INSERT INTO fpfamilies(Name) VALUES ('Actividades Fisicas y Deportivas');
INSERT INTO fpfamilies(Name) VALUES ('Administracion y Gestion');
INSERT INTO fpfamilies(Name) VALUES ('Agraria');
INSERT INTO fpfamilies(Name) VALUES ('Artes Graficas');
INSERT INTO fpfamilies(Name) VALUES ('Comercio y Marketing');
INSERT INTO fpfamilies(Name) VALUES ('Edificacion y Obra Civil');
INSERT INTO fpfamilies(Name) VALUES ('Electricidad y Electronica');
INSERT INTO fpfamilies(Name) VALUES ('Fabricacion Mecanica');
INSERT INTO fpfamilies(Name) VALUES ('Hosteleria y Turismo');
INSERT INTO fpfamilies(Name) VALUES ('Imagen Personal');
INSERT INTO fpfamilies(Name) VALUES ('Industrias Alimentarias');
INSERT INTO fpfamilies(Name) VALUES ('Informatica y Comunicaciones');
INSERT INTO fpfamilies(Name) VALUES ('Instalacion y Mantenimiento');
INSERT INTO fpfamilies(Name) VALUES ('Madera, Mueble y Corcho');
INSERT INTO fpfamilies(Name) VALUES ('Maritimo-Pesquera');
INSERT INTO fpfamilies(Name) VALUES ('Servicios Socioculturales y a la Comunidad');
INSERT INTO fpfamilies(Name) VALUES ('Textil, Confeccion y Piel');
INSERT INTO fpfamilies(Name) VALUES ('Transporte y Mantenimiento de Vehiculos');
INSERT INTO fpfamilies(Name) VALUES ('Vidrio y Ceramica');
INSERT INTO fpfamilies(Name) VALUES ('Energia y Agua');
INSERT INTO fpfamilies(Name) VALUES ('Imagen y Sonido');
INSERT INTO fpfamilies(Name) VALUES ('Industrias Extractivas');
INSERT INTO fpfamilies(Name) VALUES ('Quimica');
INSERT INTO fpfamilies(Name) VALUES ('Sanidad');
INSERT INTO fpfamilies(Name) VALUES ('Seguridad y Medio Ambiente');
INSERT INTO fpfamilies(Name) VALUES ('Artes y Artesanias');

INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Acceso y Conservacion en Instalaciones Deportivas',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Actividades Fisicas y Deportivas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Informatica de Oficina',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Administracion y Gestion'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Servicios Administrativos',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Administracion y Gestion'));        
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades Agropecuarias',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Agro-jardineria y Composiciones Florales',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Aprovechamientos Forestales',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Artes Graficas',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Artes Graficas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Servicios Comerciales',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Comercio y Marketing'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Reforma y Mantenimiento de Edificios',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Edificacion y Obra Civil'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Electricidad y Electronica',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));     
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion de Elementos Metalicos',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Instalaciones Electrotecnicas y Mecanica',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion de Elementos Metalicos',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));   
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion y Montaje',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Instalaciones Electrotecnicas y Mecanica',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades de Panaderia y Pasteleria',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Alojamiento y Lavanderia',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Cocina y Restauracion',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Peluqueria y Estetica',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades de Panaderia y Pasteleria',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Industrias Alimentarias'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Industrias Alimentarias',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Industrias Alimentarias'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Informatica de Oficina',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));       
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Informatica y Comunicaciones',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones')); 
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion y Montaje',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Viviendas',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));    
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Carpinteria y Mueble',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Madera, Mueble y Corcho'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades Maritimo-Pesqueras',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Embarcaciones Deportivas y de Recreo',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades Domesticas y Limpieza de Edificios',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Arreglo y Reparacion de Articulos Textiles y de Piel',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tapiceria y Cortinaje',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Embarcaciones Deportivas y de Recreo',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Vehiculos',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Vidrieria y Alfareria',(SELECT id FROM fpgrades WHERE name='Basica'),(SELECT id FROM fpfamilies WHERE name='Vidrio y Ceramica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades Ecuestres',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Actividades Fisicas y Deportivas'));     
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Guia en el Medio Natural y de Tiempo Libre',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Actividades Fisicas y Deportivas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Gestion Administrativa',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Administracion y Gestion'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades Ecuestres',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Aprovechamiento y Conservacion del Medio Natural',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Agraria'));   
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Jardineria y Floristeria',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Produccion Agroecologica',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Produccion Agropecuaria',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Impresion Grafica',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Artes Graficas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Postimpresion y Acabados Graficos',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Artes Graficas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Preimpresion Digital',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Artes Graficas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Actividades Comerciales',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Comercio y Marketing'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Comercializacion de Productos Alimentarios',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Comercio y Marketing'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Construccion',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Edificacion y Obra Civil'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Obras de Interior, Decoracion y Rehabilitacion',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Edificacion y Obra Civil'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Instalaciones Electricas y Automaticas',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Instalaciones de Telecomunicaciones',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Redes y Estaciones de Tratamiento de Aguas',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Energia y Agua'));  
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Conformado por Moldeo de Metales y Polimeros',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mecanizado',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Montaje de Estructuras e Instalacion de Sistemas Aeronauticos',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Soldadura y Caldereria',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Cocina y Gastronomia',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Comercializacion de Productos Alimentarios',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Servicios en Restauracion',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Estetica y Belleza',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Peluqueria y Cosmetica Capilar',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Video Disc-Jockey y Sonido',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Imagen y Sonido'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Aceites de Oliva y Vinos',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Industrias Alimentarias'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Elaboracion de Productos Alimenticios',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Industrias Alimentarias'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Panaderia, Reposteria y Confiteria',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Industrias Alimentarias')); 
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Excavaciones y Sondeos',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Industrias Extractivas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Piedra Natural',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Industrias Extractivas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Sistemas Microinformaticos y Redes',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Instalaciones Frigorificas y de Climatizacion',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Instalaciones de Produccion de Calor',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento Electromecanico',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));  
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Carpinteria y Mueble',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Madera, Mueble y Corcho'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Instalacion y Amueblamiento',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Madera, Mueble y Corcho'));        
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Procesado y Transformacion de la Madera',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Madera, Mueble y Corcho'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Cultivos Acuicolas',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento y Control de la Maquinaria de Buques y Embarcaciones',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Navegacion y Pesca de Litoral',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Operaciones Subacuaticas e Hiperbaricas',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));  
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Operaciones de Laboratorio',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Quimica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Planta Quimica',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Quimica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Emergencias Sanitarias',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Farmacia y Parafarmacia',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Emergencias y Proteccion Civil',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Seguridad y Medio Ambiente'));  
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Atencion a Personas en Situacion de Dependencia',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Calzado y Complementos de Moda',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));   
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Confeccion y Moda',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion y Ennoblecimiento de Productos Textiles',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Carroceria',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Conduccion de Vehiculos de Transporte por Carretera',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Electromecanica de Maquinaria',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Electromecanica de Vehiculos Automoviles',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Embarcaciones de Recreo',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Estructuras de Madera y Mobiliario de Embarcaciones de Recreo',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Material Rodante Ferroviario',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Montaje de Estructuras e Instalacion de Sistemas Aeronauticos',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion de Productos Ceramicos',(SELECT id FROM fpgrades WHERE name='Media'),(SELECT id FROM fpfamilies WHERE name='Vidrio y Ceramica'));       
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Acondicionamiento Fisico',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Actividades Fisicas y Deportivas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Ensenanza y Animacion Sociodeportiva',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Actividades Fisicas y Deportivas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Administracion y Finanzas',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Administracion y Gestion'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Asistencia a la Direccion',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Administracion y Gestion'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Ganaderia y Asistencia en Sanidad Animal',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Gestion Forestal y del Medio Natural',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Agraria'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Paisajismo y Medio Rural',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Agraria'));    
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Diseno y Edicion de Publicaciones Impresas y Multimedia',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Artes Graficas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Diseno y Gestion de la Produccion Grafica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Artes Graficas'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior Artista Fallero y Construccion de Escenografias',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Artes y Artesanias'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Comercio Internacional',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Comercio y Marketing'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Gestion de Ventas y Espacios Comerciales',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Comercio y Marketing'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Marketing y Publicidad',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Comercio y Marketing'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Transporte y Logistica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Comercio y Marketing'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Organizacion y Control de Obras de Construccion',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Edificacion y Obra Civil'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Proyectos de Edificacion',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Edificacion y Obra Civil'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Proyectos de Obra Civil',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Edificacion y Obra Civil'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Automatizacion y Robotica Industrial',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Electromedicina Clinica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mantenimiento Electronico',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Sistemas Electrotecnicos y Automatizados',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Sistemas de Telecomunicaciones e Informaticos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Centrales Electricas',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Energia y Agua')); 
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Eficiencia Energetica y Energia Solar Termica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Energia y Agua'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Energias Renovables',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Energia y Agua'));  
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Gestion del Agua',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Energia y Agua'));     
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Construcciones Metalicas',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Diseno en Fabricacion Mecanica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Programacion de la Produccion en Fabricacion Mecanica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Programacion de la Produccion en Moldeo de Metales y Polimeros',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Agencias de Viajes y Gestion de Eventos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Direccion de Cocina',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Direccion de Servicios de Restauracion',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Gestion de Alojamientos Turisticos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Guia, Informacion y Asistencias Turisticas',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Asesoria de Imagen Personal y Corporativa',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Caracterizacion y Maquillaje Profesional',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Estilismo y Direccion de Peluqueria',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Estetica Integral y Bienestar',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Termalismo y Bienestar',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen Personal'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Animaciones 3D, Juegos y Entornos Interactivos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen y Sonido'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Iluminacion, Captacion y Tratamiento de Imagen',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen y Sonido'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Produccion de Audiovisuales y Espectaculos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen y Sonido'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Realizacion de Proyectos Audiovisuales y Espectaculos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen y Sonido'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Sonido para Audiovisuales y Espectaculos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Imagen y Sonido'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Procesos y Calidad en la Industria Alimentaria',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Industrias Alimentarias'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Vitivinicultura',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Industrias Alimentarias'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Administracion de Sistemas Informaticos en Red',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Desarrollo de Aplicaciones Multiplataforma',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Desarrollo de Aplicaciones Web',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Desarrollo de Proyectos de Instalaciones Termicas y de Fluidos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mantenimiento de Instalaciones Termicas y de Fluidos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mecatronica Industrial',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Diseno y Amueblamiento',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Madera, Mueble y Corcho'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Acuicultura',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));       
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Organizacion del Mantenimiento de Maquinaria de Buques y Embarcaciones',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Transporte Maritimo y Pesca de Altura',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Maritimo-Pesquera'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Fabricacion de Productos Farmaceuticos, Biotecnologicos y Afines',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Quimica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Laboratorio de Analisis y de Control de Calidad',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Quimica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Quimica Industrial',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Quimica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Anatomia Patologica y Citodiagnostico',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Audiologia Protesica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));        
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Documentacion y Administracion Sanitarias',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Higiene Bucodental',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Imagen para el Diagnostico y Medicina Nuclear',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Laboratorio Clinico y Biomedico',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Ortoprotesis y Productos de Apoyo',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Protesis Dentales',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Radioterapia y Dosimetria',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Sanidad'));   
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Coordinacion de Emergencias y Proteccion Civil',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Seguridad y Medio Ambiente'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Educacion y Control Ambiental',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Seguridad y Medio Ambiente'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Quimica y Salud Ambiental',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Seguridad y Medio Ambiente'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Animacion Sociocultural y Turistica',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Educacion Infantil',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Formacion para la Movilidad Segura y Sostenible',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Integracion Social',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mediacion Comunicativa',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Promocion de Igualdad de Genero',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Servicios Socioculturales y a la Comunidad'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Diseno Textil y Piel',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Diseno y Produccion de Calzado y Complementos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Patronaje y Moda',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Vestuario a Medida y de Espectaculos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Textil, Confeccion y Piel'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Automocion',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mantenimiento Aeromecanico de Aviones con Motor de Piston',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mantenimiento Aeromecanico de Aviones con Motor de Turbina',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mantenimiento Aeromecanico de Helicopteros con Motor de Piston',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mantenimiento Aeromecanico de Helicopteros con Motor de Turbina',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Mantenimiento de Sistemas Electronicos y Avionicos de Aeronaves',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Tecnico Superior en Desarrollo y Fabricacion de Productos Ceramicos',(SELECT id FROM fpgrades WHERE name='Superior'),(SELECT id FROM fpfamilies WHERE name='Vidrio y Ceramica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Ciberseguridad en Entornos de las Tecnologias de Operacion',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Implementacion de redes 5G',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Sistemas de senalizacion y telecomunicaciones ferroviarias',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Electricidad y Electronica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion Aditiva',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Fabricacion Mecanica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Panaderia y Bolleria Artesanales',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Hosteleria y Turismo'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Audiodescripcion y Subtitulacion',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Imagen y Sonido')); 
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Inteligencia Artificial y Big Data',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Ciberseguridad en Entornos de las Tecnologias de la Informacion',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Desarrollo de videojuegos y realidad virtual',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Informatica y Comunicaciones'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Digitalizacion del Mantenimiento Industrial',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Fabricacion Inteligente',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Modelado de la informacion en la construccion (BIM)',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Instalacion y Mantenimiento'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Cultivos Celulares',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Quimica'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento de Vehiculos Hibridos y Electricos',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));
INSERT INTO fps(Name,FPGradeId,FPFamilyId)VALUES('Mantenimiento avanzado de material rodante ferroviario',(SELECT id FROM fpgrades WHERE name='Especializacion'),(SELECT id FROM fpfamilies WHERE name='Transporte y Mantenimiento de Vehiculos'));