INSERT INTO provinces (Id,Name) VALUES (02, 'Albacete');
INSERT INTO provinces (Id,Name) VALUES (03, 'Alicante/Alacant');
INSERT INTO provinces (Id,Name) VALUES (04, 'Almería');
INSERT INTO provinces (Id,Name) VALUES (01, 'Araba/Álava');
INSERT INTO provinces (Id,Name) VALUES (33, 'Asturias');
INSERT INTO provinces (Id,Name) VALUES (05, 'Ávila');
INSERT INTO provinces (Id,Name) VALUES (06, 'Badajoz');
INSERT INTO provinces (Id,Name) VALUES (07, 'Balears, Illes');
INSERT INTO provinces (Id,Name) VALUES (08, 'Barcelona');
INSERT INTO provinces (Id,Name) VALUES (48, 'Bizkaia');
INSERT INTO provinces (Id,Name) VALUES (09, 'Burgos');
INSERT INTO provinces (Id,Name) VALUES (10, 'Cáceres');
INSERT INTO provinces (Id,Name) VALUES (11, 'Cádiz');
INSERT INTO provinces (Id,Name) VALUES (39, 'Cantabria');
INSERT INTO provinces (Id,Name) VALUES (12, 'Castellón/Castelló');
INSERT INTO provinces (Id,Name) VALUES (13, 'Ciudad Real');
INSERT INTO provinces (Id,Name) VALUES (14, 'Córdoba');
INSERT INTO provinces (Id,Name) VALUES (15, 'Coruña, A');
INSERT INTO provinces (Id,Name) VALUES (16, 'Cuenca');
INSERT INTO provinces (Id,Name) VALUES (20, 'Gipuzkoa');
INSERT INTO provinces (Id,Name) VALUES (17, 'Girona');
INSERT INTO provinces (Id,Name) VALUES (18, 'Granada');
INSERT INTO provinces (Id,Name) VALUES (19, 'Guadalajara');
INSERT INTO provinces (Id,Name) VALUES (21, 'Huelva');
INSERT INTO provinces (Id,Name) VALUES (22, 'Huesca');
INSERT INTO provinces (Id,Name) VALUES (23, 'Jaén');
INSERT INTO provinces (Id,Name) VALUES (24, 'León');
INSERT INTO provinces (Id,Name) VALUES (25, 'Lleida');
INSERT INTO provinces (Id,Name) VALUES (27, 'Lugo');
INSERT INTO provinces (Id,Name) VALUES (28, 'Madrid');
INSERT INTO provinces (Id,Name) VALUES (29, 'Málaga');
INSERT INTO provinces (Id,Name) VALUES (30, 'Murcia');
INSERT INTO provinces (Id,Name) VALUES (31, 'Navarra');
INSERT INTO provinces (Id,Name) VALUES (32, 'Ourense');
INSERT INTO provinces (Id,Name) VALUES (34, 'Palencia');
INSERT INTO provinces (Id,Name) VALUES (35, 'Palmas, Las');
INSERT INTO provinces (Id,Name) VALUES (36, 'Pontevedra');
INSERT INTO provinces (Id,Name) VALUES (26, 'Rioja, La');
INSERT INTO provinces (Id,Name) VALUES (37, 'Salamanca');
INSERT INTO provinces (Id,Name) VALUES (38, 'Santa Cruz de Tenerife');
INSERT INTO provinces (Id,Name) VALUES (40, 'Segovia');
INSERT INTO provinces (Id,Name) VALUES (41, 'Sevilla');
INSERT INTO provinces (Id,Name) VALUES (42, 'Soria');
INSERT INTO provinces (Id,Name) VALUES (43, 'Tarragona');
INSERT INTO provinces (Id,Name) VALUES (44, 'Teruel');
INSERT INTO provinces (Id,Name) VALUES (45, 'Toledo');
INSERT INTO provinces (Id,Name) VALUES (46, 'Valencia/València');
INSERT INTO provinces (Id,Name) VALUES (47, 'Valladolid');
INSERT INTO provinces (Id,Name) VALUES (49, 'Zamora');
INSERT INTO provinces (Id,Name) VALUES (50, 'Zaragoza');
INSERT INTO provinces (Id,Name) VALUES (51, 'Ceuta');
INSERT INTO provinces (Id,Name) VALUES (52, 'Melilla');